name: ft_irc CI

on:
  push:
    branches: [ "main", "refactor/server-loop" ]
  pull_request:
    branches: [ "main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. GitHub 레포지토리의 코드를 가져오기
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. C++ 컴파일러(g++) 설정 및 의존성 확인
    - name: Set up C++ Environment
      run: sudo apt-get update && sudo apt-get install -y g++ make

    # 3. 프로젝트 빌드
    - name: Build ircserv
      run: make -j$(nproc)

    # 4. 백그라운드에서 irc 서버 실행
    - name: Run ircserv in background
      run: |
        ./ircserv 6667 password &
        echo "Server is running in the background."
        sleep 2

    # 5. 파이썬 테스트 스크립트 실행
    - name: Run Basic Connection Tests
      run: python3 tests/test_basic.py
